# Build a GitHub Action workflow to build a container and push it up to GHCR.io
name: Build and Push to GHCR
run-name: ${{ github.actor }} is building and pushing to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Git Short Sha
        id: git_sha
        run: echo "SHORTSHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/qemu-guest-agent:${{ steps.git_sha.outputs.SHORTSHA }},ghcr.io/${{ github.actor }}/qemu-guest-agent:fedora-41,ghcr.io/${{ github.actor }}/qemu-guest-agent:latest
